spring:
  application:
    name: todo-api
  datasource:
    url: jdbc:${DB_TYPE}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.todo.model
  type-handlers-package: com.example.todo.config
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    default-fetch-size: 100
    default-statement-timeout: 30
    configuration-properties:
      mybatis.configuration.mapUnderscoreToCamelCase: true

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
