name: CI Workflow

on:
  pull_request:
    branches: main

defaults:
  run:
    working-directory: ./api

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Spotless check
        run: ./gradlew spotlessCheck

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Run JUnit and generate coverage report
        run: ./gradlew clean test jacocoTestReport
        env:
          SPRING_PROFILES_ACTIVE: test

      - name: Verify Jacoco coverage
        run: ./gradlew jacocoTestCoverageVerification